### ISSUE TITLE
Link not followed when clicking on the confirmation button

### ISSUE THREAD

**Issue by owenders** [tavicu/bootstrap-confirmation#12]
The confirmation.DEFAULTS includes the following line at the "template" key:
```markup
'<a data-apply="confirmation" onclick="return false;">Yes</a>'
```

The problem is that because of that when we click on the confirmation button "false" is returned and the link is not followed. I think that the following line should replace it:
```markup
'<a data-apply="confirmation">Yes</a>'
```

**Comment by tavicu** [comment]
Hey,

Fixed! Thanks
