### ISSUE TITLE
Attach to future elements, or use the 'selector' option

### ISSUE THREAD

**Issue by sleepdead** [tavicu/bootstrap-confirmation#3]
Hello! 

Thanks a lot for such great plugin! It works really well and the callbacks are great!

The only drawback i'm finding is that I can't seem to find a way to attach it to future elements. I tried using the selector option, from the original tooltip, but it's buggy. 
It does attach to future elements but it looses it's natural functionality of click outside closes, and click on cancel creates another popover, in my case, to the right of the original.

I have a dynamic table with delete buttons for each row. And I can't use it on new rows. I would try to implement this but it's beyond my programming skills. 

Can you please, help?

Works for static:
```javascript
        $('[data-toggle="confirmation"]').confirmation({
            placement: 'right',
            onConfirm: removeRow,
            btnCancelLabel  : '',
            btnOkLabel      : ''
        });  
```
Doesn't work for future elements:
```javascript
        $('tbody').confirmation({
            placement: 'right',
            onConfirm: removeRow,
            selector: '[data-toggle="confirmation"]',
            btnCancelLabel  : '',
            btnOkLabel      : ''
        });
```

**Comment by jancinert** [comment]
sleepdead:
see https://github.com/tavicu/bs-confirmation/issues/16#issuecomment-148966244
